VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "coupa" do |coupa|
        coupa.vm.hostname = "coupa-assignment"
        coupa.vm.box = "ubuntu/trusty64"
        coupa.vm.network "private_network", type: "dhcp"
        config.vm.provision :shell, path: "setup.sh"
        config.vm.network :forwarded_port, guest: 80, host: 8080
        config.vm.network :forwarded_port, guest: 443, host: 8443
    end
end
        

